#!/bin/bash

NUMER_FILOZOFA=$1
LICZBA_FILOZOFOW=$2
LICZBA_POSILKOW=$3
CZAS_KONSUMOWANIA=$4
CZAS_ROZMYSLANIA=$5

function komunikat(){ 
echo "$($PWD/czas.sh) PID: $$ FILOZOF $NUMER_FILOZOFA : "
}



echo "$(komunikat) +++START+++"
sleep 5
echo "$(komunikat) +++STOP+++"
